- include: java-install.yml
- include: scala-install.yml
- include: enable-sshd.yml
- include: spark-create-user.yml
- include: spark-install.yml
- include: spark-configure.yml
- include: spark-form-cluster.yml