- include: pkg-install.yml
- include: create-users.yml
- include: python-install.yml
- include: spark-install.yml
- include: spark-configure.yml
- include: spark-form-cluster.yml
- include: jupyter-start.yml