
- name: Stop spark cluster
  shell: ./stop-all.sh
  become_user: "{{ spark_user }}"
  args:
    chdir: "{{spark_home}}/sbin"

- name: Stop history server
  shell: ./stop-history-server.sh
  become_user: "{{ spark_user }}"
  args:
    chdir: "{{spark_home}}/sbin"

- name: Start spark cluster
  shell: ./start-all.sh
  become_user: "{{ spark_user }}"
  args:
    chdir: "{{spark_home}}/sbin"